spring.application.name=vivero
spring.datasource.url=jdbc:mysql://localhost:3306/vivero_db?serverTimezone=UTC
spring.datasource.username=vivero
spring.datasource.password=vivero
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true